// ======================================================
// LEGAL DOCUMENTS (Terms & Conditions, Privacy Policy)
// ======================================================
//
// Default content for the legal.terms_and_conditions and
// legal.privacy_policy settings (see defaultSettings.js). Written
// against the platform's actual features - update these texts
// whenever a feature they describe changes.
//
// The frontend keeps an identical copy in
// client/lib/legalDocuments.js (shown when the settings are empty),
// because client and server are separate packages. Keep both files
// identical. When changing a default here, also add the replaced
// version's SHA-256 to seeders/settingsSeeder.js so existing
// databases still holding the old default get upgraded.
//
// Format (also what admins use when editing in Settings -> Legal):
//   "1. Heading"  -> bold section heading
//   "- text"      -> bullet point
//   other lines   -> paragraph
// Rendered by renderLegalDocument() in LegalHelpContent.jsx.
//
// Items in [SQUARE BRACKETS] are placeholders for business
// details that must be filled in before publishing.

const TERMS_AND_CONDITIONS = `By creating an account or using Gamzzones, you agree to these Terms and our Privacy Policy.

1. Account Usage
- You must be 18 or older, and real-money gaming must be legal where you live. Checking this is your responsibility.
- One account per person. Your details, payment methods and payout accounts must be your own.
- Keep your password and OTPs private. You are responsible for all activity on your account.

2. Deposits & Withdrawals
- Deposits are made in INR within the limits shown, through Razorpay or a manual payment reference that our team verifies.
- Only your real balance can be withdrawn - bonus and test balances cannot. Withdrawals are paid to your own bank account or UPI ID.
- The withdrawal amount is held while your request is processed. If it is rejected or fails, the full amount is returned.

3. Withdrawal Fees
- Up to ₹1,000: 0% | Above ₹1,000: 1% | Above ₹5,000: 1.5% | Above ₹10,000: 2%.
- Your total withdrawals for the day, including the new one, decide the fee tier. The fee is deducted from the amount paid out.
- The exact fee and the amount you will receive are shown before you confirm. Rates may change; the Withdrawal page always shows the current rates.

4. Betting & Game Rules
- Place one bet per round on Red, Green or Blue within the bet limits. You may increase it on the same colour while more than 5 seconds remain. Bets cannot be cancelled.
- Results are generated by our server after betting closes. Depending on our settings, either the colour with the lowest total amount bet by all players wins (ties decided at random), or a colour is chosen at random.
- A winning bet pays your stake times the multiplier shown in the game; a losing bet loses the stake. Cancelled rounds are refunded. Winnings are never guaranteed.

5. User Responsibilities
- Play only with money you can afford to lose. Contact Support if you want your account blocked or closed.
- Do not use multiple accounts, bots, collusion, bug exploits or other people's payment details, or abuse bonuses and referrals.

6. Account Suspension
- We may suspend or close accounts, hold withdrawals while we investigate, and reverse bets, bonuses or winnings gained through fraud, abuse or errors.
- On closure, your withdrawable real balance is paid out unless withheld for fraud or legal reasons. Bonus and test balances are forfeited.

7. Terms Changes
- We may update these Terms and platform settings such as limits and fees. Changes are posted on this page, and continued use means you accept them.

8. Support & Disputes
- For any issue, open a support ticket with details such as the round number or payment reference. Our server records are used to resolve disputes.
- Contact: [SUPPORT EMAIL] | [LEGAL ENTITY NAME], [REGISTERED ADDRESS]. Governing law: [JURISDICTION].`;


const PRIVACY_POLICY = `This policy explains what personal data Gamzzones collects and how it is used and protected.

1. Information We Collect
- Account details: your name, username, email, optional mobile number and password (stored only in hashed form).
- Activity: wallet balances, transactions, bets and results, referrals, notifications and support tickets.
- Payment details you provide: deposit references and payout details (bank account and IFSC, or UPI ID).

2. How We Use Information
- To run your account, wallet and games, process deposits and withdrawals, and send OTPs and notifications.
- To provide support, prevent fraud and abuse, and meet legal obligations. The public leaderboard shows only your username and rank.

3. Payment & Security Information
- Online payments are processed by Razorpay; we do not store your card details. We keep the payment references, statuses and payout details needed to process your transactions.

4. Cookies & Session Data
- We use your browser's storage to keep you signed in and remember preferences such as your cookie choice. We do not use advertising or analytics tracking.

5. Data Sharing
- We do not sell your data. We share it only with providers that help run Gamzzones (Razorpay, our email provider and hosting providers), or when required by law.

6. Data Security
- We use hashed passwords and OTPs, login limits, rate limiting and restricted admin access. No system is completely secure, so keep your login details private.

7. User Rights
- You can view and update your profile in Settings, and request a copy, correction or deletion of your data through Support. Some records must be kept for legal and fraud-prevention reasons.

8. Policy Changes & Contact
- We may update this policy and will post changes on this page. Questions: [PRIVACY EMAIL] or open a support ticket.`;


module.exports = {
    TERMS_AND_CONDITIONS,
    PRIVACY_POLICY,
};
